VAGUE_WORDS = [
    "fast","quick","rapid","efficient","efficiently","easy","easily","simple","simply",
    "user-friendly","friendly","intuitive","smooth","seamless","powerful","robust",
    "flexible","scalable","secure","safely","optimized","optimal","high-quality",
    "reliable","reliably","responsive","convenient","smart","advanced","modern",
    "appropriate","suitable","acceptable","sufficient","effective","effectively",
    "improved","improve","better","best","good","great","excellent","perfect",
    "bad","poor","reasonable","adequate","minimal","maximum","normal","proper",
    "properly","correct","correctly","accurate","accurately","relevant","useful",
    "helpful","meaningful","significant","important","critical","major","minor",
    "certain","various","multiple","many","several","few","some","all","enough",
    "frequently","often","sometimes","occasionally","rarely","usually","normally",
    "instantly","immediately","soon","shortly","timely","real-time","dynamic",
    "dynamically","automatically","automatic","manual","recent","latest","updated",
    "optimized","stable","consistent","consistently","smoothly","securely","high",
    "low","large","small","tiny","huge","massive","lightweight","heavy","complex",
    "complicated","clear","clearly","understandable","readable","maintainable",
    "professional","personalized","customized","tailored","satisfactory","usable",
    "accessible","available","unavailable","temporary","permanent","common","generic",
    "specific","appropriate","suspicious","unusual","unexpected","expected",
    "validated","verified","trustworthy","trusted","confidential","sensitive",
    "authorized","unauthorized","prioritized","optimized","preferred","recommended",
    "suitable","manageable","flexibly","adaptable","portable","compatible",
    "incompatible","sufficiently","adequately","partially","fully","partially-complete",
    "complete","incomplete","successful","successfully","unsuccessful","safe","unsafe",
    "visible","hidden","transparent","relevant","irrelevant","engaging","interactive",
    "productive","productive","high-performance","low-latency","scalable","responsive",
    "performant","clean","cleanly","organized","well-structured","structured",
    "optimized-performance","light","heavy-duty","feature-rich","intelligent",
    "intelligently","predictive","smartly","fastest","slow","slower","slowly",
    "near","far","higher","lower","best-effort","reasonable-time","minimal-delay",
    "low-risk","high-risk","appropriate-time","suitable-format","good-quality",
    "bad-quality","friendly-interface","easy-to-use","easy-access","easy-navigation",
    "easy-management","simple-process","quick-access","quick-response","rapid-response",
    "fast-loading","secure-access","safe-access","better-performance","improved-security",
    "enhanced","enhancement","optimized-security","optimized-performance","satisfactory-result",
    "acceptable-result","desired","desired-state","sufficient-performance",
    "reliable-service","reliable-system","stable-performance","stable-system",
    "efficient-process","effective-process","convenient-access","proper-format",
    "proper-validation","proper-handling","suitable-response","timely-notification",
    "timely-response","correct-behavior","normal-behavior","expected-behavior",
    "unexpected-behavior","good-experience","better-experience","smooth-experience",
    "intuitive-interface","modern-interface","advanced-features","high-priority",
    "low-priority","reasonable-limit","acceptable-limit","significant-delay",
    "minimal-effort","minimal-input","few-clicks","many-options","appropriate-action",
    "suitable-option","manageable-workload","proper-security","strong-security",
    "highly-secure","highly-available","fault-tolerant","future-proof","state-of-the-art",
    "world-class","enterprise-grade","industry-standard","optimized-workflow",
    "efficient-workflow","easy-workflow","flexible-workflow","quickly","rapidly",
    "smooth-transition","smart-recommendation","good-visibility","clear-view",
    "better-control","easy-control","simple-access","minimal-time","low-complexity",
    "high-complexity","appropriate-level","sufficient-data","reasonable-amount",
    "proper-integration","suitable-integration","high-speed","low-speed","best-practice",
    "optimized-storage","optimized-query","optimized-search","easy-search","fast-search",
    "convenient-checkout","secure-payment","quick-checkout","reliable-payment",
    "improved-navigation","improved-accessibility","better-usability","better-visibility",
    "high-accuracy","low-accuracy","reasonable-accuracy","acceptable-accuracy",
    "fast-processing","efficient-processing","timely-processing","secure-processing",
    "appropriate-message","clear-message","meaningful-message","helpful-message",
    "relevant-content","dynamic-content","appropriate-content","quality-content",
    "good-design","modern-design","professional-design","clean-design","minimal-design",
    "advanced-security","enhanced-security","optimized-system","better-system",
    "stable-connection","reliable-connection","smooth-operation","good-performance",
    "high-performance","low-performance","optimized-experience","friendly-navigation",
    "easy-registration","easy-login","simple-checkout","quick-payment","fast-delivery",
    "timely-delivery","reliable-delivery","safe-delivery","appropriate-permissions",
    "sufficient-logging","proper-monitoring","good-monitoring","reasonable-retry",
    "intelligent-routing","smart-filtering","efficient-filtering","advanced-search",
    "better-search","quick-results","instant-results","meaningful-results",
    "optimized-results","desired-results","satisfactory-performance","acceptable-performance",
    # =----------------------
    "appropriate-size","appropriate-speed","appropriate-layout","appropriate-access",
    "appropriate-security","appropriate-level","appropriate-interface","appropriate-data",
    "appropriate-timeframe","appropriate-response","appropriate-workflow","appropriate-format",
    "acceptable-speed","acceptable-security","acceptable-performance","acceptable-delay",
    "acceptable-interface","acceptable-availability","acceptable-output","acceptable-quality",
    "acceptable-usage","acceptable-experience","acceptable-workflow","acceptable-design",
    "reasonable-speed","reasonable-security","reasonable-performance","reasonable-load",
    "reasonable-response","reasonable-time","reasonable-size","reasonable-quality",
    "reasonable-amount","reasonable-workflow","reasonable-usage","reasonable-behavior",
    "sufficient-security","sufficient-performance","sufficient-speed","sufficient-logging",
    "sufficient-monitoring","sufficient-validation","sufficient-capacity","sufficient-storage",
    "adequate-security","adequate-performance","adequate-speed","adequate-validation",
    "adequate-monitoring","adequate-support","adequate-storage","adequate-visibility",
    "high-speed","high-capacity","high-volume","high-load","high-priority",
    "high-availability","high-reliability","high-flexibility","high-scalability",
    "high-usability","high-security","high-visibility","high-efficiency",
    "low-latency","low-delay","low-risk","low-overhead","low-complexity",
    "low-effort","low-maintenance","low-memory","low-resource","low-bandwidth",
    "minimal-clicks","minimal-delay","minimal-effort","minimal-input","minimal-wait",
    "minimal-steps","minimal-processing","minimal-overhead","minimal-errors",
    "maximum-speed","maximum-security","maximum-performance","maximum-efficiency",
    "better-navigation","better-security","better-speed","better-interface",
    "better-layout","better-processing","better-visibility","better-monitoring",
    "improved-performance","improved-security","improved-workflow","improved-layout",
    "improved-response","improved-experience","improved-visibility","improved-monitoring",
    "enhanced-performance","enhanced-security","enhanced-visibility","enhanced-monitoring",
    "enhanced-accessibility","enhanced-usability","enhanced-navigation","enhanced-control",
    "optimized-layout","optimized-navigation","optimized-interface","optimized-query",
    "optimized-workflow","optimized-security","optimized-storage","optimized-processing",
    "optimized-loading","optimized-search","optimized-access","optimized-validation",
    "quick-loading","quick-processing","quick-navigation","quick-validation",
    "quick-verification","quick-response","quick-search","quick-access",
    "rapid-processing","rapid-loading","rapid-search","rapid-navigation",
    "rapid-response","rapid-access","rapid-validation","rapid-verification",
    "instant-access","instant-response","instant-loading","instant-results",
    "instant-validation","instant-notification","instant-feedback","instant-update",
    "timely-update","timely-alert","timely-notification","timely-processing",
    "timely-response","timely-delivery","timely-validation","timely-action",
    "dynamic-layout","dynamic-content","dynamic-behavior","dynamic-interface",
    "dynamic-navigation","dynamic-updates","dynamic-validation","dynamic-filtering",
    "flexible-layout","flexible-filtering","flexible-navigation","flexible-processing",
    "flexible-validation","flexible-search","flexible-reporting","flexible-settings",
    "smart-navigation","smart-filtering","smart-processing","smart-validation",
    "smart-routing","smart-search","smart-monitoring","smart-alerts",
    "advanced-navigation","advanced-search","advanced-filtering","advanced-processing",
    "advanced-monitoring","advanced-validation","advanced-reporting","advanced-control",
    "modern-layout","modern-interface","modern-design","modern-navigation",
    "modern-workflow","modern-validation","modern-processing","modern-search",
    "simple-layout","simple-navigation","simple-interface","simple-processing",
    "simple-validation","simple-search","simple-settings","simple-management",
    "easy-navigation","easy-interface","easy-access","easy-processing",
    "easy-management","easy-validation","easy-configuration","easy-monitoring",
    "friendly-layout","friendly-interface","friendly-navigation","friendly-workflow",
    "friendly-search","friendly-validation","friendly-processing","friendly-monitoring",
    "smooth-navigation","smooth-processing","smooth-validation","smooth-search",
    "smooth-loading","smooth-transition","smooth-workflow","smooth-experience",
    "seamless-navigation","seamless-processing","seamless-validation","seamless-search",
    "seamless-integration","seamless-transition","seamless-access","seamless-workflow",
    "robust-validation","robust-security","robust-processing","robust-monitoring",
    "robust-search","robust-storage","robust-reporting","robust-access",
    "powerful-search","powerful-processing","powerful-validation","powerful-monitoring",
    "powerful-filtering","powerful-reporting","powerful-security","powerful-control",
    "stable-performance","stable-connection","stable-processing","stable-search",
    "stable-validation","stable-storage","stable-interface","stable-navigation",
    "reliable-processing","reliable-storage","reliable-validation","reliable-search",
    "reliable-notifications","reliable-monitoring","reliable-delivery","reliable-service",
    "secure-storage","secure-access","secure-processing","secure-validation",
    "secure-navigation","secure-reporting","secure-transactions","secure-connections",
    "safe-processing","safe-storage","safe-navigation","safe-validation",
    "safe-transactions","safe-access","safe-integration","safe-handling",
    "professional-interface","professional-layout","professional-design","professional-navigation",
    "professional-processing","professional-reporting","professional-validation","professional-workflow",
    "clean-layout","clean-interface","clean-navigation","clean-processing",
    "clean-validation","clean-reporting","clean-storage","clean-monitoring",
    "clear-navigation","clear-layout","clear-interface","clear-processing",
    "clear-validation","clear-reporting","clear-feedback","clear-visibility",
    "meaningful-results","meaningful-feedback","meaningful-alerts","meaningful-notifications",
    "meaningful-processing","meaningful-reporting","meaningful-validation","meaningful-insights",
    "useful-results","useful-feedback","useful-notifications","useful-alerts",
    "useful-validation","useful-monitoring","useful-processing","useful-reporting",
    "relevant-results","relevant-content","relevant-feedback","relevant-alerts",
    "relevant-insights","relevant-notifications","relevant-processing","relevant-monitoring",
    "efficient-routing","efficient-search","efficient-processing","efficient-validation",
    "efficient-reporting","efficient-storage","efficient-loading","efficient-navigation",
    "effective-search","effective-processing","effective-validation","effective-monitoring",
    "effective-reporting","effective-navigation","effective-storage","effective-routing",
    "fast-search","fast-processing","fast-loading","fast-navigation",
    "fast-validation","fast-filtering","fast-monitoring","fast-reporting",
    "convenient-access","convenient-processing","convenient-validation","convenient-search",
    "convenient-checkout","convenient-navigation","convenient-reporting","convenient-management",
    "scalable-storage","scalable-processing","scalable-validation","scalable-monitoring",
    "scalable-reporting","scalable-navigation","scalable-search","scalable-workflow",
    "responsive-layout","responsive-interface","responsive-navigation","responsive-processing",
    "responsive-validation","responsive-search","responsive-filtering","responsive-workflow",
    "intelligent-processing","intelligent-routing","intelligent-validation","intelligent-monitoring",
    "intelligent-filtering","intelligent-search","intelligent-alerts","intelligent-reporting",
    "future-ready","future-proof","industry-standard","enterprise-grade",
    "world-class","next-generation","best-in-class","cutting-edge",
    "state-of-the-art","mission-critical","business-critical","production-ready"
]
SAFE_WORDS = [
"user","users","customer","customers","buyer","buyers","seller","sellers","shopper","shoppers",
"admin","administrator","administrators","manager","managers","staff","agent","agents","analyst",
"analysts","moderator","moderators","reviewer","reviewers","developer","developers","engineer",
"engineers","coordinator","officer","support","team","teams","member","members","vendor","vendors",
"partner","partners","consumer","consumers","merchant","merchants","operator","operators",

"product","products","item","items","catalog","catalogs","category","categories","listing","listings",
"inventory","stock","stocks","warehouse","warehouses","cart","carts","wishlist","checkout","payment",
"payments","invoice","invoices","receipt","receipts","shipment","shipments","delivery","deliveries",
"refund","refunds","return","returns","coupon","coupons","discount","discounts","promotion",
"promotions","campaign","campaigns","offer","offers","bundle","bundles","package","packages",
"purchase","purchases","transaction","transactions","order","orders","subscription","subscriptions",
"billing","tax","taxes","currency","wallet","wallets","payout","payouts","settlement","settlements",
"tracking","fulfillment","dispatch","pickup","carrier","carriers","marketplace","store","stores",
"storefront","shop","shops","brand","brands","supplier","suppliers","channel","channels",

"account","accounts","profile","profiles","session","sessions","login","logout","password",
"authentication","authorization","permission","permissions","role","roles","access","api","apis",
"endpoint","endpoints","token","tokens","database","databases","server","servers","cache","caches",
"webhook","webhooks","integration","integrations","platform","platforms","system","systems",
"service","services","application","applications","module","modules","component","components",
"interface","interfaces","dashboard","dashboards","notification","notifications","message",
"messages","alert","alerts","report","reports","analytics","metric","metrics","statistics",
"history","logs","record","records","dataset","datasets","schema","schemas","pipeline","pipelines",
"workflow","workflows","queue","queues","event","events","activity","activities","audit","audits",
"compliance","verification","validation","monitoring","governance","configuration","configurations",

"image","images","video","videos","media","content","banner","banners","document","documents",
"file","files","attachment","attachments","template","templates","theme","themes","layout",
"layouts","page","pages","section","sections","menu","menus","widget","widgets","search","filter",
"filters","sort","sorting","query","queries","keyword","keywords","tag","tags","label","labels",

"address","addresses","location","locations","region","regions","country","countries","language",
"languages","translation","translations","localization","timezone","timezones",

"fraud","security","privacy","encryption","certificate","certificates","compliance","policy",
"policies","regulation","regulations","rule","rules","restriction","restrictions","credential",
"credentials","verification","authentication","authorization","consent","permissions",

"create","creates","created","creating","update","updates","updated","updating","delete","deletes",
"deleted","deleting","submit","submits","submitted","submitting","approve","approves","approved",
"reject","rejects","rejected","validate","validates","validated","validating","calculate",
"calculates","calculated","calculating","generate","generates","generated","generating","track",
"tracks","tracked","tracking","monitor","monitors","monitored","monitoring","search","searches",
"searched","searching","filter","filters","filtered","filtering","sort","sorts","sorted","sorting",
"upload","uploads","uploaded","uploading","download","downloads","downloaded","downloading",
"export","exports","exported","exporting","import","imports","imported","importing","save","saves",
"saved","saving","store","stores","stored","storing","load","loads","loaded","loading","display",
"displays","displayed","displaying","show","shows","shown","showing","send","sends","sent",
"sending","receive","receives","received","receiving","process","processes","processed",
"processing","execute","executes","executed","executing","schedule","schedules","scheduled",
"scheduling","assign","assigns","assigned","assigning","notify","notifies","notified","notifying",
"refresh","refreshes","refreshed","refreshing","archive","archives","archived","archiving",
"restore","restores","restored","restoring","compare","compares","compared","comparing",
"analyze","analyzes","analyzed","analyzing","review","reviews","reviewed","reviewing","detect",
"detects","detected","detecting","identify","identifies","identified","identifying","publish",
"publishes","published","publishing","configure","configures","configured","configuring",

"active","inactive","enabled","disabled","pending","processed","completed","failed","successful",
"unsuccessful","available","unavailable","open","closed","visible","hidden","public","private",
"online","offline","current","previous","existing","new","latest","final","temporary","permanent",
"draft","archived","verified","approved","rejected","scheduled","assigned","unassigned",

"response","responses","request","requests","feedback","ticket","tickets","comment","comments",
"review","reviews","rating","ratings","summary","summaries","overview","details","description",
"descriptions","information","data","value","values","amount","amounts","quantity","quantities",
"price","prices","total","totals","count","counts","score","scores","result","results","status",
"statuses","state","states","priority","priorities","threshold","thresholds","option","options",
"setting","settings","parameter","parameters","preference","preferences","method","methods",
"type","types","version","versions","identifier","identifiers","reference","references","code",
"codes","number","numbers","date","dates","timestamp","timestamps","duration","durations",
# -----------------------
"accordion","adapter","adapters","addon","addons","aggregation","allocator","android","announcement",
"announcements","app","apps","artifact","artifacts","ascii","asset","assets","assistant","assistants",
"attachment","attachments","attribute","attributes","autocomplete","avatar","avatars","backend",
"backends","backup","backups","barcode","barcodes","baseline","batch","batches","breadcrumb",
"breadcrumbs","browser","browsers","buffer","buffers","build","builds","button","buttons","byte",
"bytes","callback","callbacks","captcha","captchas","card","cards","carousel","carousels","cell",
"cells","certificate","certificates","challenge","challenges","checkbox","checkboxes","classifier",
"classifiers","client","clients","clipboard","cluster","clusters","cms","connector","connectors",
"container","containers","controller","controllers","cookie","cookies","cron","csv","cursor",
"cursors","daemon","daemons","dependency","dependencies","deployment","deployments","dialog",
"dialogs","directory","directories","dns","docker","domain","domains","dropdown","dropdowns",
"editor","editors","element","elements","emulator","emulators","encoder","encoders","enrollment",
"environment","environments","exception","exceptions","extension","extensions","favicon","feature",
"features","feed","feeds","field","fields","firewall","firewalls","firmware","flag","flags",
"folder","folders","font","fonts","footer","footers","framework","frameworks","frontend",
"frontends","function","functions","gateway","gateways","graphql","grid","grids","group","groups",
"gzip","handler","handlers","header","headers","hook","hooks","hostname","hostnames","html","http",
"https","icon","icons","index","indexes","instance","instances","ios","ipv4","ipv6","javascript",
"jpeg","jpg","json","kernel","kernels","library","libraries","listener","listeners","loader",
"loaders","locale","locales","localhost","mapper","mappers","markdown","middleware","migration",
"migrations","mock","mocks","namespace","namespaces","navbar","node","nodes","oauth","object",
"objects","observer","observers","operand","operands","parser","parsers","patch","patches","pdf",
"plugin","plugins","png","pointer","pointers","popup","popups","port","ports","processor",
"processors","proxy","proxies","python","radio","radios","react","reactjs","redis","registry",
"registries","renderer","renderers","repository","repositories","resolver","resolvers","resource",
"resources","router","routers","runtime","sandbox","sdk","selector","selectors","serializer",
"serializers","sidebar","sidebars","slider","sliders","snippet","snippets","socket","sockets",
"source","sources","spinner","spinners","sprite","sprites","sql","sqlite","stack","stacks",
"stylesheet","stylesheets","svg","switch","switches","syntax","tab","tabs","table","tables",
"textarea","thread","threads","thumbnail","thumbnails","tls","toolbar","toolbars","tooltip",
"tooltips","trace","traces","tree","trees","trigger","triggers","ui","uml","unicode","uri","url",
"urls","usb","validator","validators","viewport","viewports","vm","vms","websocket","websockets",
"window","windows","xml","yaml","zip","zipcode","cpu","gpu","ram","ssd","hostname","localhost",
"microservice","microservices","orchestrator","orchestrators","scheduler","schedulers","tenant",
"tenants","workspace","workspaces","tenantid","userid","username","usernames","fullname",
"firstname","lastname","middlename","zipcode","postalcode","phone","phones","mobile","mobiles",
"telephone","telephones","fax","birthdate","gender","avatar","avatars","nickname","nicknames",
"biography","bio","organization","organizations","department","departments","designation",
"designations","employee","employees","attendance","payroll","invoiceid","orderid","productid",
"sku","skus","barcode","barcodes","shipmentid","trackingid","paymentid","transactionid","uuid",
"uuids","guid","guids","checksum","checksums","hash","hashes","tokenization","serializer",
"serialization","deserialization","normalization","optimizer","optimizers","predictor",
"predictors","classifier","classifiers","embedding","embeddings","transformer","transformers",
"tokenizer","tokenizers","vector","vectors","vectorizer","vectorizers","matrix","matrices",
"pipeline","pipelines","checkpoint","checkpoints","epoch","epochs","dataset","datasets","batching",
"finetuning","preprocessing","postprocessing","inference","inferencing","segmentation","clustering",
"regression","classification","multilabel","multiclass","binary","probability","probabilities",
"featuremap","featuremaps","heatmap","heatmaps","histogram","histograms","timeseries",
"forecast","forecasts","telemetry","telemetries","throughput","latency","bandwidth","uptime",
"downtime","heartbeat","heartbeats","watchdog","watchdogs","handshake","handshakes","failover",
"rollback","rollbacks","checkpointing","snapshot","snapshots","replica","replicas","sharding",
"partition","partitions","replication","deduplication","compression","decompression","encryption",
"decryption","signing","signature","signatures","certificate","certificates","authenticator",
"authenticators","authorizer","authorizers","comparator","comparators","aggregator","aggregators",
"formatter","formatters","generator","generators","extractor","extractors","collector",
"collectors","dispatcher","dispatchers","synchronizer","synchronizers","initializer",
"initializers","executor","executors","compiler","compilers","interpreter","interpreters",
"debugger","debuggers","profiler","profilers","benchmark","benchmarks","scanner","scanners",
"crawler","crawlers","scraper","scrapers","listener","listeners","subscriber","subscribers",
"publisher","publishers","broadcaster","broadcasters","cachekey","cachekeys","lookup","lookups",
"manifest","manifests","playbook","playbooks","blueprint","blueprints","workspaceid",
"organizationid","tenantkey","apikey","clientid","secretkey","accesskey","refreshkey",
"checksumid","buildid","releaseid","deploymentid","pipelineid","sessionid","traceid","spanid",
"requestid","responseid","eventid","notificationid","messageid","conversationid","threadid"
]
# result = [item for item in VAGUE_WORDS if item not in SAFE_WORDS]
# print(len(VAGUE_WORDS))
# print(len(SAFE_WORDS))
# print(len(result))
VAGUE_WORDS = ['fast', 'quick', 'rapid', 'efficient', 'efficiently', 'easy', 'easily', 'simple', 'simply', 'user-friendly', 'friendly', 'intuitive', 'smooth', 'seamless', 'powerful', 'robust', 'flexible', 'scalable', 'secure', 'safely', 'optimized', 'optimal', 'high-quality', 'reliable', 'reliably', 'responsive', 'convenient', 'smart', 'advanced', 'modern', 'appropriate', 'suitable', 'acceptable', 'sufficient', 'effective', 'effectively', 'improved', 'improve', 'better', 'best', 'good', 'great', 'excellent', 'perfect', 'bad', 'poor', 'reasonable', 'adequate', 'minimal', 'maximum', 'normal', 'proper', 'properly', 'correct', 'correctly', 'accurate', 'accurately', 'relevant', 'useful', 'helpful', 'meaningful', 'significant', 'important', 'critical', 'major', 'minor', 'certain', 'various', 'multiple', 'many', 'several', 'few', 'some', 'all', 'enough', 'frequently', 'often', 'sometimes', 'occasionally', 'rarely', 'usually', 'normally', 'instantly', 'immediately', 'soon', 'shortly', 'timely', 'real-time', 'dynamic', 'dynamically', 'automatically', 'automatic', 'manual', 'recent', 'optimized', 'stable', 'consistent', 'consistently', 'smoothly', 'securely', 'high', 'low', 'large', 'small', 'tiny', 'huge', 'massive', 'lightweight', 'heavy', 'complex', 'complicated', 'clear', 'clearly', 'understandable', 'readable', 'maintainable', 'professional', 'personalized', 'customized', 'tailored', 'satisfactory', 'usable', 'accessible', 'common', 'generic', 'specific', 'appropriate', 'suspicious', 'unusual', 'unexpected', 'expected', 'trustworthy', 'trusted', 'confidential', 'sensitive', 'authorized', 'unauthorized', 'prioritized', 'optimized', 'preferred', 'recommended', 'suitable', 'manageable', 'flexibly', 'adaptable', 'portable', 'compatible', 'incompatible', 'sufficiently', 'adequately', 'partially', 'fully', 'partially-complete', 'complete', 'incomplete', 'successfully', 'safe', 'unsafe', 'transparent', 'relevant', 'irrelevant', 'engaging', 'interactive', 'productive', 'productive', 'high-performance', 'low-latency', 'scalable', 'responsive', 'performant', 'clean', 'cleanly', 'organized', 'well-structured', 'structured', 'optimized-performance', 'light', 'heavy-duty', 'feature-rich', 'intelligent', 'intelligently', 'predictive', 'smartly', 'fastest', 'slow', 'slower', 'slowly', 'near', 'far', 'higher', 'lower', 'best-effort', 'reasonable-time', 'minimal-delay', 'low-risk', 'high-risk', 'appropriate-time', 'suitable-format', 'good-quality', 'bad-quality', 'friendly-interface', 'easy-to-use', 'easy-access', 'easy-navigation', 'easy-management', 'simple-process', 'quick-access', 'quick-response', 'rapid-response', 'fast-loading', 'secure-access', 'safe-access', 'better-performance', 'improved-security', 'enhanced', 'enhancement', 'optimized-security', 'optimized-performance', 'satisfactory-result', 'acceptable-result', 'desired', 'desired-state', 'sufficient-performance', 'reliable-service', 'reliable-system', 'stable-performance', 'stable-system', 'efficient-process', 'effective-process', 'convenient-access', 'proper-format', 'proper-validation', 'proper-handling', 'suitable-response', 'timely-notification', 'timely-response', 'correct-behavior', 'normal-behavior', 'expected-behavior', 'unexpected-behavior', 'good-experience', 'better-experience', 'smooth-experience', 'intuitive-interface', 'modern-interface', 'advanced-features', 'high-priority', 'low-priority', 'reasonable-limit', 'acceptable-limit', 'significant-delay', 'minimal-effort', 'minimal-input', 'few-clicks', 'many-options', 'appropriate-action', 'suitable-option', 'manageable-workload', 'proper-security', 'strong-security', 'highly-secure', 'highly-available', 'fault-tolerant', 'future-proof', 'state-of-the-art', 'world-class', 'enterprise-grade', 'industry-standard', 'optimized-workflow', 'efficient-workflow', 'easy-workflow', 'flexible-workflow', 'quickly', 'rapidly', 'smooth-transition', 'smart-recommendation', 'good-visibility', 'clear-view', 'better-control', 'easy-control', 'simple-access', 'minimal-time', 'low-complexity', 'high-complexity', 'appropriate-level', 'sufficient-data', 'reasonable-amount', 'proper-integration', 'suitable-integration', 'high-speed', 'low-speed', 'best-practice', 'optimized-storage', 'optimized-query', 'optimized-search', 'easy-search', 'fast-search', 'convenient-checkout', 'secure-payment', 'quick-checkout', 'reliable-payment', 'improved-navigation', 'improved-accessibility', 'better-usability', 'better-visibility', 'high-accuracy', 'low-accuracy', 'reasonable-accuracy', 'acceptable-accuracy', 'fast-processing', 'efficient-processing', 'timely-processing', 'secure-processing', 'appropriate-message', 'clear-message', 'meaningful-message', 'helpful-message', 'relevant-content', 'dynamic-content', 'appropriate-content', 'quality-content', 'good-design', 'modern-design', 'professional-design', 'clean-design', 'minimal-design', 'advanced-security', 'enhanced-security', 'optimized-system', 'better-system', 'stable-connection', 'reliable-connection', 'smooth-operation', 'good-performance', 'high-performance', 'low-performance', 'optimized-experience', 'friendly-navigation', 'easy-registration', 'easy-login', 'simple-checkout', 'quick-payment', 'fast-delivery', 'timely-delivery', 'reliable-delivery', 'safe-delivery', 'appropriate-permissions', 'sufficient-logging', 'proper-monitoring', 'good-monitoring', 'reasonable-retry', 'intelligent-routing', 'smart-filtering', 'efficient-filtering', 'advanced-search', 'better-search', 'quick-results', 'instant-results', 'meaningful-results', 'optimized-results', 'desired-results', 'satisfactory-performance', 'acceptable-performance', 'appropriate-size', 'appropriate-speed', 'appropriate-layout', 'appropriate-access', 'appropriate-security', 'appropriate-level', 'appropriate-interface', 'appropriate-data', 'appropriate-timeframe', 'appropriate-response', 'appropriate-workflow', 'appropriate-format', 'acceptable-speed', 'acceptable-security', 'acceptable-performance', 'acceptable-delay', 'acceptable-interface', 'acceptable-availability', 'acceptable-output', 'acceptable-quality', 'acceptable-usage', 'acceptable-experience', 'acceptable-workflow', 'acceptable-design', 'reasonable-speed', 'reasonable-security', 'reasonable-performance', 'reasonable-load', 'reasonable-response', 'reasonable-time', 'reasonable-size', 'reasonable-quality', 'reasonable-amount', 'reasonable-workflow', 'reasonable-usage', 'reasonable-behavior', 'sufficient-security', 'sufficient-performance', 'sufficient-speed', 'sufficient-logging', 'sufficient-monitoring', 'sufficient-validation', 'sufficient-capacity', 'sufficient-storage', 'adequate-security', 'adequate-performance', 'adequate-speed', 'adequate-validation', 'adequate-monitoring', 'adequate-support', 'adequate-storage', 'adequate-visibility', 'high-speed', 'high-capacity', 'high-volume', 'high-load', 'high-priority', 'high-availability', 'high-reliability', 'high-flexibility', 'high-scalability', 'high-usability', 'high-security', 'high-visibility', 'high-efficiency', 'low-latency', 'low-delay', 'low-risk', 'low-overhead', 'low-complexity', 'low-effort', 'low-maintenance', 'low-memory', 'low-resource', 'low-bandwidth', 'minimal-clicks', 'minimal-delay', 'minimal-effort', 'minimal-input', 'minimal-wait', 'minimal-steps', 'minimal-processing', 'minimal-overhead', 'minimal-errors', 'maximum-speed', 'maximum-security', 'maximum-performance', 'maximum-efficiency', 'better-navigation', 'better-security', 'better-speed', 'better-interface', 'better-layout', 'better-processing', 'better-visibility', 'better-monitoring', 'improved-performance', 'improved-security', 'improved-workflow', 'improved-layout', 'improved-response', 'improved-experience', 'improved-visibility', 'improved-monitoring', 'enhanced-performance', 'enhanced-security', 'enhanced-visibility', 'enhanced-monitoring', 'enhanced-accessibility', 'enhanced-usability', 'enhanced-navigation', 'enhanced-control', 'optimized-layout', 'optimized-navigation', 'optimized-interface', 'optimized-query', 'optimized-workflow', 'optimized-security', 'optimized-storage', 'optimized-processing', 'optimized-loading', 'optimized-search', 'optimized-access', 'optimized-validation', 'quick-loading', 'quick-processing', 'quick-navigation', 'quick-validation', 'quick-verification', 'quick-response', 'quick-search', 'quick-access', 'rapid-processing', 'rapid-loading', 'rapid-search', 'rapid-navigation', 'rapid-response', 'rapid-access', 'rapid-validation', 'rapid-verification', 'instant-access', 'instant-response', 'instant-loading', 'instant-results', 'instant-validation', 'instant-notification', 'instant-feedback', 'instant-update', 'timely-update', 'timely-alert', 'timely-notification', 'timely-processing', 'timely-response', 'timely-delivery', 'timely-validation', 'timely-action', 'dynamic-layout', 'dynamic-content', 'dynamic-behavior', 'dynamic-interface', 'dynamic-navigation', 'dynamic-updates', 'dynamic-validation', 'dynamic-filtering', 'flexible-layout', 'flexible-filtering', 'flexible-navigation', 'flexible-processing', 'flexible-validation', 'flexible-search', 'flexible-reporting', 'flexible-settings', 'smart-navigation', 'smart-filtering', 'smart-processing', 'smart-validation', 'smart-routing', 'smart-search', 'smart-monitoring', 'smart-alerts', 'advanced-navigation', 'advanced-search', 'advanced-filtering', 'advanced-processing', 'advanced-monitoring', 'advanced-validation', 'advanced-reporting', 'advanced-control', 'modern-layout', 'modern-interface', 'modern-design', 'modern-navigation', 'modern-workflow', 'modern-validation', 'modern-processing', 'modern-search', 'simple-layout', 'simple-navigation', 'simple-interface', 'simple-processing', 'simple-validation', 'simple-search', 'simple-settings', 'simple-management', 'easy-navigation', 'easy-interface', 'easy-access', 'easy-processing', 'easy-management', 'easy-validation', 'easy-configuration', 'easy-monitoring', 'friendly-layout', 'friendly-interface', 'friendly-navigation', 'friendly-workflow', 'friendly-search', 'friendly-validation', 'friendly-processing', 'friendly-monitoring', 'smooth-navigation', 'smooth-processing', 'smooth-validation', 'smooth-search', 'smooth-loading', 'smooth-transition', 'smooth-workflow', 'smooth-experience', 'seamless-navigation', 'seamless-processing', 'seamless-validation', 'seamless-search', 'seamless-integration', 'seamless-transition', 'seamless-access', 'seamless-workflow', 'robust-validation', 'robust-security', 'robust-processing', 'robust-monitoring', 'robust-search', 'robust-storage', 'robust-reporting', 'robust-access', 'powerful-search', 'powerful-processing', 'powerful-validation', 'powerful-monitoring', 'powerful-filtering', 'powerful-reporting', 'powerful-security', 'powerful-control', 'stable-performance', 'stable-connection', 'stable-processing', 'stable-search', 'stable-validation', 'stable-storage', 'stable-interface', 'stable-navigation', 'reliable-processing', 'reliable-storage', 'reliable-validation', 'reliable-search', 'reliable-notifications', 'reliable-monitoring', 'reliable-delivery', 'reliable-service', 'secure-storage', 'secure-access', 'secure-processing', 'secure-validation', 'secure-navigation', 'secure-reporting', 'secure-transactions', 'secure-connections', 'safe-processing', 'safe-storage', 'safe-navigation', 'safe-validation', 'safe-transactions', 'safe-access', 'safe-integration', 'safe-handling', 'professional-interface', 'professional-layout', 'professional-design', 'professional-navigation', 'professional-processing', 'professional-reporting', 'professional-validation', 'professional-workflow', 'clean-layout', 'clean-interface', 'clean-navigation', 'clean-processing', 'clean-validation', 'clean-reporting', 'clean-storage', 'clean-monitoring', 'clear-navigation', 'clear-layout', 'clear-interface', 'clear-processing', 'clear-validation', 'clear-reporting', 'clear-feedback', 'clear-visibility', 'meaningful-results', 'meaningful-feedback', 'meaningful-alerts', 'meaningful-notifications', 'meaningful-processing', 'meaningful-reporting', 'meaningful-validation', 'meaningful-insights', 'useful-results', 'useful-feedback', 'useful-notifications', 'useful-alerts', 'useful-validation', 'useful-monitoring', 'useful-processing', 'useful-reporting', 'relevant-results', 'relevant-content', 'relevant-feedback', 'relevant-alerts', 'relevant-insights', 'relevant-notifications', 'relevant-processing', 'relevant-monitoring', 'efficient-routing', 'efficient-search', 'efficient-processing', 'efficient-validation', 'efficient-reporting', 'efficient-storage', 'efficient-loading', 'efficient-navigation', 'effective-search', 'effective-processing', 'effective-validation', 'effective-monitoring', 'effective-reporting', 'effective-navigation', 'effective-storage', 'effective-routing', 'fast-search', 'fast-processing', 'fast-loading', 'fast-navigation', 'fast-validation', 'fast-filtering', 'fast-monitoring', 'fast-reporting', 'convenient-access', 'convenient-processing', 'convenient-validation', 'convenient-search', 'convenient-checkout', 'convenient-navigation', 'convenient-reporting', 'convenient-management', 'scalable-storage', 'scalable-processing', 'scalable-validation', 'scalable-monitoring', 'scalable-reporting', 'scalable-navigation', 'scalable-search', 'scalable-workflow', 'responsive-layout', 'responsive-interface', 'responsive-navigation', 'responsive-processing', 'responsive-validation', 'responsive-search', 'responsive-filtering', 'responsive-workflow', 'intelligent-processing', 'intelligent-routing', 'intelligent-validation', 'intelligent-monitoring', 'intelligent-filtering', 'intelligent-search', 'intelligent-alerts', 'intelligent-reporting', 'future-ready', 'future-proof', 'industry-standard', 'enterprise-grade', 'world-class', 'next-generation', 'best-in-class', 'cutting-edge', 'state-of-the-art', 'mission-critical', 'business-critical', 'production-ready']

# print(len(VAGUE_WORDS))

def dublicateCount(list):
    seen = set()
    duplicates = set()
    for x in list:
        if x in seen:
            duplicates.add(x)
        else:
            seen.add(x)
    return {
        "count" : len(duplicates),
        "duplicates" : duplicates
    }

def intersection(list1, list2):
    common = [item for item in list1 if item in list2]
    return common

def difference(list1,list2):
    difference = [item for item in list1 if item not in list2]
    return difference

# print(dublicateCount(VAGUE_WORDS)["count"])
# duplicates = dublicateCount(SAFE_WORDS)["count"]
# print(duplicates)

# newlist = list(set(SAFE_WORDS))
# print(newlist)

VAGUE_WORDS = ['reliable-delivery', 'quick-payment', 'suitable-response', 'high-usability', 'responsive-layout', 'expected', 'robust', 'smooth-processing', 'appropriate-interface', 'low-complexity', 'rapid-processing', 'reliable', 'efficient-process', 'reasonable-security', 'powerful-control', 'optimized-navigation', 'excellent', 'improved', 'modern-layout', 'clear-navigation', 'high-risk', 'huge', 'specific', 'optimized-processing', 'many-options', 'professional-workflow', 'clean-validation', 'poor', 'automatic', 'safe-delivery', 'improved-security', 'minimal-processing', 'low-accuracy', 'various', 'safe-transactions', 'useful-monitoring', 'intelligent-monitoring', 'secure-access', 'flexible-validation', 'clean-layout', 'sufficient-security', 'future-proof', 'responsive-validation', 'convenient-search', 'proper-integration', 'convenient-reporting', 'reasonable-usage', 'clear-reporting', 'scalable-storage', 'shortly', 'maximum-efficiency', 'efficient-validation', 'minimal-errors', 'seamless', 'accessible', 'relevant-content', 'some', 'several', 'low-delay', 'powerful-security', 'reasonable-load', 'clean-monitoring', 'critical', 'appropriate-timeframe', 'complicated', 'reasonable-limit', 'dynamic-interface', 'meaningful-message', 'satisfactory-performance', 'quick-results', 'improved-response', 'helpful', 'efficient-reporting', 'good', 'relevant', 'acceptable-speed', 'modern-validation', 'smooth-operation', 'secure-storage', 'high-volume', 'flexible-workflow', 'seamless-processing', 'reasonable-size', 'relevant-monitoring', 'minimal-input', 'dynamic', 'minimal-delay', 'meaningful-notifications', 'best-in-class', 'simple-management', 'cutting-edge', 'clean', 'consistent', 'fast-navigation', 'robust-storage', 'improved-accessibility', 'instant-response', 'acceptable-availability', 'normal-behavior', 'reliable-storage', 'reliable-search', 'normal', 'effective-reporting', 'safely', 'proper-validation', 'advanced-validation', 'minimal-clicks', 'major', 'modern', 'interactive', 'partially-complete', 'intelligent-routing', 'normally', 'complete', 'stable-connection', 'sufficient-storage', 'responsive-navigation', 'intelligent', 'fast-loading', 'appropriate-format', 'rapid-verification', 'responsive', 'quick-access', 'friendly-navigation', 'enhanced', 'fast', 'secure-processing', 'secure', 'simple-process', 'state-of-the-art', 'desired-state', 'safe-navigation', 'adequate-security', 'friendly-interface', 'safe-validation', 'advanced-monitoring', 'recommended', 'easy-processing', 'friendly-monitoring', 'improved-experience', 'properly', 'professional-layout', 'meaningful-validation', 'better-visibility', 'flexible-layout', 'well-structured', 'intelligent-reporting', 'generic', 'suitable-integration', 'friendly-search', 'advanced-filtering', 'optimized-layout', 'complex', 'fault-tolerant', 'easy-registration', 'fast-monitoring', 'modern-workflow', 'sufficient-performance', 'professional-navigation', 'useful-alerts', 'feature-rich', 'low-speed', 'flexible-navigation', 'reasonable-quality', 'convenient', 'effective-navigation', 'smart-alerts', 'dynamic-content', 'acceptable-limit', 'appropriate-layout', 'safe-processing', 'timely', 'customized', 'high-priority', 'adaptable', 'optimized-access', 'adequate-visibility', 'easy-login', 'accurately', 'better-search', 'useful-validation', 'multiple', 'high-performance', 'optimized-interface', 'easily', 'intelligently', 'secure-validation', 'accurate', 'appropriate-speed', 'reliable-notifications', 'responsive-search', 'reasonable-retry', 'adequate-support', 'portable', 'strong-security', 'satisfactory-result', 'instant-loading', 'manual', 'optimized-experience', 'adequate', 'dynamically', 'safe-handling', 'proper-security', 'best-practice', 'enhanced-performance', 'robust-reporting', 'simple', 'friendly', 'sometimes', 'structured', 'higher', 'enhanced-accessibility', 'rapid-search', 'advanced', 'high-efficiency', 'smooth-loading', 'fully', 'scalable-monitoring', 'manageable', 'flexible', 'prioritized', 'easy-workflow', 'efficient-workflow', 'sufficient-monitoring', 'instant-update', 'suitable', 'proper-handling', 'easy-control', 'smart-search', 'clear-message', 'slowly', 'future-ready', 'significant-delay', 'reasonable-time', 'adequate-validation', 'stable-navigation', 'intelligent-alerts', 'convenient-validation', 'reliable-monitoring', 'effective-process', 'improved-workflow', 'professional-interface', 'advanced-features', 'friendly-processing', 'efficient', 'advanced-control', 'high-speed', 'industry-standard', 'engaging', 'acceptable-interface', 'automatically', 'perfect', 'convenient-checkout', 'production-ready', 'minimal-design', 'few', 'small', 'dynamic-behavior', 'efficient-routing', 'mission-critical', 'optimized', 'heavy-duty', 'quick-verification', 'clear-view', 'smart-validation', 'timely-response', 'advanced-security', 'advanced-search', 'improved-layout', 'high-load', 'powerful-validation', 'convenient-processing', 'appropriate-security', 'advanced-reporting', 'productive', 'robust-validation', 'instant-access', 'highly-available', 'bad', 'appropriate-content', 'appropriate-action', 'seamless-transition', 'large', 'stable', 'fast-validation', 'easy-management', 'meaningful-insights', 'quick-loading', 'acceptable-workflow', 'powerful-filtering', 'smart-filtering', 'rapid-access', 'seamless-workflow', 'trustworthy', 'easy', 'effective-processing', 'smart-routing', 'easy-configuration', 'robust-security', 'preferred', 'better-experience', 'sufficiently', 'better-system', 'recent', 'better-navigation', 'clean-navigation', 'correct-behavior', 'flexible-processing', 'organized', 'simple-navigation', 'stable-interface', 'smartly', 'timely-validation', 'smart-processing', 'reliable-processing', 'stable-system', 'minimal', 'scalable-processing', 'improved-navigation', 'quickly', 'improve', 'enhanced-visibility', 'flexible-reporting', 'reasonable', 'low-latency', 'low-resource', 'rapid-navigation', 'meaningful-reporting', 'sufficient-data', 'minimal-wait', 'professional', 'appropriate', 'business-critical', 'dynamic-navigation', 'useful-reporting', 'useful', 'reasonable-amount', 'next-generation', 'safe-storage', 'efficiently', 'irrelevant', 'transparent', 'robust-access', 'bad-quality', 'convenient-access', 'easy-validation', 'personalized', 'modern-navigation', 'appropriate-time', 'flexible-settings', 'modern-search', 'high-complexity', 'smart-navigation', 'world-class', 'adequately', 'reliable-service', 'partially', 'instant-results', 'useful-results', 'enough', 'desired-results', 'successfully', 'acceptable-quality', 'powerful-monitoring', 'professional-design', 'better-performance', 'simple-access', 'enterprise-grade', 'soon', 'stable-validation', 'easy-access', 'stable-search', 'high-security', 'tiny', 'best', 'reliable-payment', 'enhanced-security', 'scalable-reporting', 'better-processing', 'meaningful-processing', 'acceptable-performance', 'high-visibility', 'powerful', 'robust-processing', 'enhanced-monitoring', 'reasonable-speed', 'minimal-effort', 'acceptable-experience', 'minimal-overhead', 'rapid-response', 'instant-feedback', 'fastest', 'acceptable-delay', 'smooth-search', 'maximum-speed', 'significant', 'low', 'readable', 'better-control', 'maximum', 'safe', 'reasonable-accuracy', 'expected-behavior', 'fast-delivery', 'acceptable', 'timely-update', 'clean-storage', 'acceptable-security', 'powerful-reporting', 'effective-monitoring', 'quick-checkout', 'high-availability', 'scalable-navigation', 'secure-navigation', 'seamless-validation', 'appropriate-response', 'intelligent-search', 'rarely', 'far', 'better', 'unauthorized', 'clean-design', 'scalable', 'optimized-security', 'optimized-query', 'maximum-performance', 'good-quality', 'professional-processing', 'optimized-workflow', 'all', 'high', 'high-accuracy', 'acceptable-result', 'timely-delivery', 'simple-checkout', 'fast-filtering', 'intelligent-processing', 'seamless-navigation', 'effective', 'important', 'effective-validation', 'appropriate-message', 'quality-content', 'optimized-validation', 'better-speed', 'simple-settings', 'clear-layout', 'massive', 'efficient-storage', 'quick-processing', 'meaningful-feedback', 'friendly-validation', 'meaningful-alerts', 'acceptable-usage', 'quick', 'optimized-storage', 'easy-navigation', 'correct', 'adequate-speed', 'appropriate-size', 'useful-notifications', 'improved-monitoring', 'useful-feedback', 'easy-monitoring', 'optimized-search', 'optimized-loading', 'simple-processing', 'smart-recommendation', 'enhanced-navigation', 'effectively', 'user-friendly', 'helpful-message', 'clean-reporting', 'minor', 'seamless-access', 'better-layout', 'often', 'efficient-navigation', 'maintainable', 'appropriate-level', 'sensitive', 'quick-response', 'professional-validation', 'high-scalability', 'responsive-workflow', 'safe-integration', 'proper', 'timely-processing', 'satisfactory', 'incomplete', 'relevant-notifications', 'unexpected-behavior', 'better-security', 'responsive-filtering', 'performant', 'best-effort', 'clear-validation', 'correctly', 'heavy', 'easy-search', 'confidential', 'high-capacity', 'stable-performance', 'proper-monitoring', 'responsive-processing', 'instantly', 'improved-performance', 'rapidly', 'low-risk', 'convenient-management', 'powerful-processing', 'robust-monitoring', 'highly-secure', 'sufficient', 'tailored', 'low-bandwidth', 'securely', 'relevant-insights', 'proper-format', 'responsive-interface', 'clean-processing', 'intuitive', 'many', 'smart', 'easy-to-use', 'certain', 'good-visibility', 'good-monitoring', 'relevant-processing', 'adequate-storage', 'unsafe', 'robust-search', 'cleanly', 'powerful-search', 'sufficient-speed', 'lower', 'quick-validation', 'smart-monitoring', 'suitable-format', 'efficient-loading', 'authorized', 'maximum-security', 'reliable-connection', 'minimal-steps', 'enhancement', 'secure-transactions', 'smoothly', 'occasionally', 'suitable-option', 'secure-payment', 'sufficient-logging', 'fast-reporting', 'dynamic-validation', 'smooth-experience', 'stable-storage', 'secure-connections', 'modern-processing', 'smooth-workflow', 'dynamic-updates', 'high-quality', 'consistently', 'timely-notification', 'easy-interface', 'usable', 'appropriate-data', 'friendly-workflow', 'instant-validation', 'seamless-integration', 'common', 'low-maintenance', 'secure-reporting', 'smooth-validation', 'unusual', 'dynamic-filtering', 'optimized-system', 'enhanced-control', 'stable-processing', 'good-design', 'low-memory', 'simple-validation', 'relevant-feedback', 'clear-interface', 'high-reliability', 'optimized-performance', 'intuitive-interface', 'reasonable-performance', 'reliably', 'advanced-navigation', 'intelligent-validation', 'appropriate-workflow', 'clear-feedback', 'low-effort', 'effective-storage', 'appropriate-access', 'rapid-loading', 'understandable', 'clear-processing', 'reasonable-behavior', 'slow', 'simple-interface', 'real-time', 'clean-interface', 'low-priority', 'friendly-layout', 'advanced-processing', 'acceptable-design', 'smooth-navigation', 'flexible-search', 'lightweight', 'slower', 'near', 'scalable-search', 'optimized-results', 'clearly', 'flexible-filtering', 'appropriate-permissions', 'fast-processing', 'better-monitoring', 'better-usability', 'clear-visibility', 'acceptable-accuracy', 'convenient-navigation', 'sufficient-validation', 'improved-visibility', 'sufficient-capacity', 'safe-access', 'few-clicks', 'great', 'efficient-filtering', 'manageable-workload', 'high-flexibility', 'enhanced-usability', 'incompatible', 'modern-design', 'quick-search', 'clear', 'effective-search', 'relevant-alerts', 'flexibly', 'acceptable-output', 'effective-routing', 'efficient-processing', 'simple-layout', 'adequate-monitoring', 'intelligent-filtering', 'unexpected', 'simply', 'smooth-transition', 'scalable-validation', 'modern-interface', 'compatible', 'seamless-search', 'desired', 'efficient-search', 'adequate-performance', 'meaningful', 'reasonable-workflow', 'good-performance', 'suspicious', 'simple-search', 'timely-alert', 'rapid-validation', 'fast-search', 'trusted', 'timely-action', 'professional-reporting', 'quick-navigation', 'useful-processing', 'reasonable-response', 'low-performance', 'smooth', 'light', 'minimal-time', 'frequently', 'dynamic-layout', 'optimal', 'reliable-system', 'good-experience', 'instant-notification', 'rapid', 'relevant-results', 'reliable-validation', 'immediately', 'usually', 'better-interface', 'predictive', 'meaningful-results', 'low-overhead', 'scalable-workflow']

# print(dublicateCount(VAGUE_WORDS)["count"])
# print(len(VAGUE_WORDS))
SAFE_WORDS = ['items', 'successful', 'profiler', 'textarea', 'cpu', 'return', 'font', 'disabled', 'saving', 'captcha', 'ascii', 'operator', 'uuids', 'permission', 'private', 'cell', 'server', 'multiclass', 'source', 'checkpoint', 'archives', 'backend', 'crawlers', 'role', 'version', 'router', 'agent', 'encoders', 'directories', 'billing', 'callbacks', 'analyzing', 'create', 'viewport', 'optimizer', 'calculates', 'message', 'yaml', 'shown', 'admin', 'processor', 'handshake', 'attribute', 'taxes', 'domain', 'serializers', 'videos', 'metrics', 'assigning', 'invoiceid', 'histograms', 'icons', 'dropdown', 'toolbars', 'zip', 'inference', 'asset', 'receipts', 'platform', 'configured', 'aggregation', 'domains', 'shows', 'displaying', 'sorted', 'publishers', 'transformer', 'descriptions', 'tooltips', 'mappers', 'price', 'generate', 'priority', 'ports', 'metric', 'loaded', 'language', 'database', 'track', 'objects', 'reports', 'failover', 'rejected', 'reviewing', 'date', 'refreshing', 'index', 'endpoint', 'receipt', 'consumers', 'validates', 'collector', 'snapshots', 'pages', 'feedback', 'interpreter', 'deploymentid', 'platforms', 'regression', 'radio', 'update', 'online', 'scores', 'attachments', 'loads', 'compares', 'cursors', 'subscription', 'roles', 'validating', 'unavailable', 'certificates', 'allocator', 'syntax', 'servers', 'modules', 'comments', 'forecast', 'containers', 'existing', 'total', 'privacy', 'settings', 'moderators', 'registry', 'aggregator', 'popups', 'amounts', 'executors', 'load', 'identified', 'template', 'sent', 'campaigns', 'approves', 'reviewers', 'json', 'bytes', 'snapshot', 'calculated', 'open', 'functions', 'authentication', 'vector', 'folders', 'ssd', 'profilers', 'groups', 'totals', 'processed', 'localhost', 'sources', 'compilers', 'watchdog', 'benchmarks', 'consent', 'promotions', 'detected', 'extractor', 'port', 'validator', 'statuses', 'checkpointing', 'sidebar', 'vendor', 'workflows', 'inventory', 'reference', 'latest', 'quantities', 'data', 'document', 'toolbar', 'cookies', 'request', 'accordion', 'checkboxes', 'synchronizer', 'tracked', 'imported', 'sending', 'parameters', 'switches', 'products', 'states', 'payments', 'jpg', 'mock', 'brands', 'pipeline', 'observer', 'shopper', 'wallets', 'epoch', 'store', 'formatter', 'identifier', 'kernels', 'submit', 'generator', 'authorizers', 'tokenizers', 'item', 'login', 'records', 'tokenizer', 'service', 'parser', 'themes', 'compiler', 'zipcode', 'queues', 'storing', 'module', 'executor', 'function', 'extension', 'channels', 'numbers', 'paymentid', 'tree', 'components', 'registries', 'seller', 'shipments', 'application', 'threads', 'client', 'loader', 'fax', 'csv', 'closed', 'cookie', 'telephone', 'popup', 'normalization', 'classification', 'comparing', 'timezones', 'video', 'grids', 'baseline', 'classifier', 'emulators', 'code', 'libraries', 'xml', 'productid', 'footer', 'shipmentid', 'subscriptions', 'buildid', 'filtering', 'developer', 'connectors', 'pointer', 'challenges', 'builds', 'vendors', 'stylesheet', 'binary', 'scanners', 'hidden', 'option', 'enabled', 'serializer', 'validate', 'scheduling', 'overview', 'artifacts', 'container', 'deleting', 'replicas', 'credential', 'slider', 'details', 'messageid', 'app', 'analyze', 'payout', 'checkbox', 'android', 'displays', 'members', 'gender', 'buyer', 'browser', 'process', 'svg', 'configurations', 'featuremaps', 'histogram', 'postalcode', 'radios', 'playbook', 'marketplace', 'menus', 'translations', 'crawler', 'docker', 'carousels', 'encoder', 'javascript', 'sprites', 'developers', 'cards', 'build', 'filters', 'hook', 'group', 'resources', 'initializer', 'callback', 'buffer', 'pickup', 'notification', 'dashboard', 'gateway', 'batch', 'validated', 'observers', 'nickname', 'scanner', 'record', 'displayed', 'identifying', 'png', 'python', 'rollback', 'benchmark', 'latency', 'sdk', 'trackingid', 'stored', 'synchronizers', 'interfaces', 'exporting', 'uri', 'bio', 'statistics', 'creating', 'loading', 'checkpoints', 'keyword', 'react', 'system', 'subscriber', 'tls', 'flags', 'viewports', 'watchdogs', 'queries', 'saves', 'published', 'previous', 'triggers', 'middleware', 'biography', 'refreshed', 'sharding', 'mobile', 'listings', 'staff', 'stocks', 'tax', 'services', 'ipv4', 'optimizers', 'reviews', 'reactjs', 'routers', 'rollbacks', 'restore', 'employees', 'conversationid', 'menu', 'workspaces', 'deserialization', 'predictors', 'restriction', 'ratings', 'directory', 'sliders', 'compliance', 'analysts', 'information', 'socket', 'duration', 'frontends', 'description', 'brand', 'cart', 'temporary', 'updates', 'dialog', 'handler', 'snippets', 'localization', 'elements', 'telephones', 'generated', 'formatters', 'probability', 'regulation', 'thresholds', 'datasets', 'folder', 'workspaceid', 'environment', 'feed', 'patch', 'trees', 'governance', 'manifest', 'reviewed', 'address', 'layouts', 'avatar', 'events', 'usb', 'replica', 'administrator', 'tenant', 'event', 'breadcrumbs', 'comment', 'state', 'approve', 'vectorizers', 'merchant', 'requests', 'coupon', 'review', 'receives', 'gateways', 'locations', 'inferencing', 'merchants', 'publishes', 'serialization', 'tab', 'vectorizer', 'traceid', 'discount', 'public', 'daemons', 'refreshes', 'finetuning', 'aggregators', 'export', 'responses', 'preference', 'carousel', 'vms', 'widgets', 'middlename', 'catalogs', 'integrations', 'addons', 'carts', 'amount', 'thumbnail', 'barcodes', 'restores', 'processing', 'listener', 'rejects', 'clipboard', 'encryption', 'unsuccessful', 'status', 'offline', 'users', 'backups', 'frontend', 'unicode', 'extractors', 'saved', 'package', 'product', 'offer', 'session', 'clients', 'interface', 'payroll', 'library', 'autocomplete', 'repositories', 'resource', 'switch', 'configuration', 'pdf', 'buyers', 'buttons', 'summary', 'classifiers', 'guid', 'checksumid', 'firewalls', 'translation', 'grid', 'alerts', 'banners', 'fonts', 'buffers', 'nodes', 'renderers', 'markdown', 'api', 'alert', 'filtered', 'plugin', 'tenants', 'sandbox', 'region', 'nicknames', 'deployment', 'save', 'transactions', 'checksum', 'phone', 'matrices', 'barcode', 'mocks', 'settlement', 'operand', 'search', 'predictor', 'url', 'draft', 'notificationid', 'tenantkey', 'notifies', 'departments', 'spinners', 'file', 'sessions', 'detects', 'resolver', 'invoice', 'dataset', 'tag', 'thread', 'identifiers', 'team', 'policy', 'bundle', 'upload', 'instances', 'priorities', 'showing', 'migrations', 'proxies', 'filter', 'executing', 'offers', 'sends', 'notifying', 'pointers', 'orchestrators', 'downloads', 'webhook', 'segmentation', 'visible', 'partners', 'feature', 'proxy', 'restrictions', 'hash', 'lastname', 'fulfillment', 'prices', 'wishlist', 'cursor', 'throughput', 'validators', 'sellers', 'reject', 'transaction', 'assistants', 'notified', 'warehouses', 'labels', 'payment', 'tokens', 'urls', 'runtime', 'hostname', 'organizationid', 'indexes', 'publishing', 'dns', 'replication', 'publisher', 'sql', 'authorization', 'listeners', 'integration', 'order', 'method', 'query', 'pipelineid', 'html', 'messages', 'trace', 'downtime', 'notifications', 'counts', 'searches', 'websocket', 'ios', 'promotion', 'templates', 'spinner', 'partitions', 'matrix', 'cells', 'component', 'databases', 'executed', 'cron', 'ram', 'cluster', 'attachment', 'report', 'images', 'partner', 'exported', 'imports', 'detecting', 'verified', 'stylesheets', 'analyzes', 'probabilities', 'storefront', 'preprocessing', 'usernames', 'debugger', 'namespace', 'image', 'tokenization', 'currency', 'updated', 'codes', 'profiles', 'layout', 'gpu', 'type', 'guids', 'byte', 'sections', 'account', 'element', 'endpoints', 'configure', 'references', 'deletes', 'namespaces', 'editors', 'widget', 'webhooks', 'download', 'analyzed', 'vm', 'uuid', 'identify', 'refreshkey', 'discounts', 'extensions', 'apps', 'microservice', 'enrollment', 'send', 'announcement', 'response', 'threshold', 'assigned', 'heatmap', 'heatmaps', 'archiving', 'dispatch', 'artifact', 'publish', 'versions', 'settlements', 'pipelines', 'deployments', 'checksums', 'created', 'label', 'refresh', 'policies', 'editor', 'threadid', 'orders', 'available', 'sprite', 'final', 'password', 'regulations', 'results', 'teams', 'mapper', 'systems', 'captchas', 'backup', 'inactive', 'batching', 'analytics', 'calculating', 'options', 'migration', 'updating', 'sku', 'emulator', 'certificate', 'tags', 'generating', 'validation', 'rule', 'shoppers', 'lookups', 'debuggers', 'deliveries', 'footers', 'comparator', 'schemas', 'blueprints', 'comparators', 'pending', 'embeddings', 'firstname', 'requestid', 'scheduled', 'submitted', 'configures', 'organizations', 'importing', 'deleted', 'decryption', 'values', 'environments', 'microservices', 'queue', 'telemetries', 'countries', 'bandwidth', 'https', 'unassigned', 'manager', 'coordinator', 'methods', 'page', 'executes', 'summaries', 'lookup', 'profile', 'audit', 'count', 'parsers', 'adapter', 'dropdowns', 'stock', 'exceptions', 'tenantid', 'engineers', 'dashboards', 'windows', 'table', 'eventid', 'signing', 'monitors', 'tracking', 'show', 'selector', 'officer', 'backends', 'handlers', 'dispatcher', 'hooks', 'favicon', 'member', 'display', 'partition', 'graphql', 'import', 'feeds', 'responseid', 'forecasts', 'challenge', 'schedule', 'agents', 'fraud', 'calculate', 'mobiles', 'sockets', 'token', 'designations', 'refunds', 'category', 'timezone', 'releaseid', 'clustering', 'plugins', 'scraper', 'fullname', 'media', 'durations', 'selectors', 'languages', 'score', 'vectors', 'types', 'permissions', 'active', 'firewall', 'featuremap', 'current', 'icon', 'embedding', 'applications', 'breadcrumb', 'authorizer', 'avatars', 'logs', 'regions', 'cachekey', 'restoring', 'accesskey', 'downloading', 'moderator', 'analyst', 'channel', 'schedules', 'orchestrator', 'handshakes', 'checkout', 'headers', 'heartbeat', 'window', 'completed', 'warehouse', 'managers', 'apis', 'generates', 'notify', 'sessionid', 'jpeg', 'rules', 'carrier', 'controllers', 'gzip', 'documents', 'firmware', 'organization', 'assistant', 'multilabel', 'restored', 'execute', 'oauth', 'epochs', 'addon', 'blueprint', 'uml', 'reviewer', 'apikey', 'dependencies', 'detect', 'consumer', 'parameter', 'exports', 'assigns', 'payouts', 'processors', 'user', 'invoices', 'monitoring', 'suppliers', 'approved', 'uploading', 'assign', 'broadcasters', 'patches', 'tabs', 'tickets', 'monitored', 'initializers', 'cache', 'packages', 'stacks', 'heartbeats', 'delivery', 'userid', 'caches', 'received', 'resolvers', 'dispatchers', 'transformers', 'ticket', 'spanid', 'sidebars', 'receiving', 'fields', 'frameworks', 'configuring', 'bundles', 'receive', 'adapters', 'banner', 'features', 'shops', 'searched', 'snippet', 'stack', 'history', 'cms', 'searching', 'http', 'postprocessing', 'secretkey', 'clusters', 'sqlite', 'administrators', 'purchase', 'support', 'compared', 'deduplication', 'subscribers', 'submits', 'skus', 'refund', 'carriers', 'preferences', 'instance', 'exception', 'department', 'number', 'trigger', 'timestamp', 'batches', 'redis', 'archive', 'setting', 'files', 'dependency', 'manifests', 'operators', 'button', 'cachekeys', 'location', 'card', 'uploads', 'traces', 'transactionid', 'header', 'purchases', 'security', 'delete', 'kernel', 'interpreters', 'broadcaster', 'scheduler', 'quantity', 'attendance', 'ui', 'username', 'accounts', 'audits', 'workspace', 'controller', 'daemon', 'uploaded', 'downloaded', 'announcements', 'object', 'listing', 'monitor', 'schedulers', 'coupons', 'ipv6', 'result', 'timestamps', 'assets', 'loaders', 'campaign', 'telemetry', 'generators', 'engineer', 'sorts', 'locales', 'framework', 'hostnames', 'theme', 'orderid', 'schema', 'identifies', 'creates', 'tracks', 'signature', 'catalog', 'wallet', 'logout', 'failed', 'country', 'submitting', 'customers', 'uptime', 'tables', 'access', 'flag', 'operands', 'keywords', 'navbar', 'categories', 'shop', 'new', 'websockets', 'stores', 'supplier', 'compare', 'field', 'section', 'addresses', 'collectors', 'tooltip', 'hashes', 'archived', 'workflow', 'authenticators', 'thumbnails', 'rating', 'dates', 'activities', 'shipment', 'content', 'permanent', 'clientid', 'signatures', 'returns', 'activity', 'authenticator', 'verification', 'connector', 'attributes', 'designation', 'birthdate', 'credentials', 'phones', 'employee', 'decompression', 'playbooks', 'browsers', 'node', 'sorting', 'compression', 'scrapers', 'processes', 'customer', 'value', 'locale', 'renderer', 'dialogs', 'timeseries', 'sort', 'repository']

# print(dublicateCount(SAFE_WORDS)["count"])
# print(len(SAFE_WORDS))

# from tqdm import tqdm
# import time
# import pandas as pd
# from backend.modules.validator import is_polysemous


# df = pd.read_excel(r"e_comerence_us_synthetic_data_set_4635.xlsx")


# false_positive_words = []

# stories = df["user_story"].to_list()

# # story = stories.iloc[0]
# # false_positive_words.append(is_polysemous(story))
# for story in tqdm(stories):
#     words = is_polysemous(story)
#     if words:
#         false_positive_words.extend(words)


# print(len(false_positive_words))
# list= set(false_positive_words)
# print(len(list))
# print(list)
listx = {'exchanged', 'trusted', 'initiated', 'join', 'rings', 'previews', 'remain', 'resume', 'moving', 'angles', 'pickups', 'sharing', 'suspended', 'proof', 'trends', 'expose', 'edited', 'placements', 'selection', 'reflected', 'adding', 'acknowledge', 'certain', 'misuse', 'spam', 'coordination', 'execution', 'cohorts', 'log', 'arrivals', 'like', 'continuing', 'estimate', 'emphasized', 'translated', 'alignment', 'timing', 'structure', 'irregularities', 'come', 'deliver', 'suspect', 'recommended', 'fee', 'live', 'integrate', 'acknowledgments', 'transitions', 'exceed', 'engaging', 'wise', 'started', 'border', 'correspondence', 'acknowledged', 'test', 'spend', 'top', 'protection', 'term', 'range', 'requested', 'center', 'standard', 'day', 'launch', 'supervised', 'registered', 'offensive', 'accessories', 'persistent', 'party', 'render', 'capabilities', 'oversight', 'responsibility', 'continues', 'present', 'coverage', 'screens', 'exemptions', 'feel', 'combinations', 'transferred', 'revised', 'expense', 'funds', 'peak', 'selections', 'operate', 'arrangements', 'reported', 'training', 'ask', 'measured', 'marked', 'persistence', 'corrections', 'usable', 'fulfill', 'match', 'investment', 'connection', 'indexing', 'testing', 'compromise', 'cause', 'taxonomy', 'replacements', 'days', 'familiar', 'storage', 'overwhelmed', 'dead', 'bank', 'parallel', 'tools', 'protected', 'requesting', 'destinations', 'focus', 'potential', 'completing', 'patterns', 'work', 'scoring', 'normal', 'disruptions', 'ranking', 'collapse', 'budgets', 'posture', 'modifications', 'typing', 'dedicated', 'quality', 'timely', 'exposure', 'overlapping', 'verify', 'left', 'portion', 'contains', 'varied', 'modify', 'merge', 'satisfaction', 'unified', 'much', 'denied', 'duplicate', 'resolutions', 'automation', 'preparation', 'advance', 'distributed', 'units', 'explanation', 'stream', 'communication', 'demand', 'breaking', 'task', 'normalize', 'inquiries', 'violate', 'first', 'pays', 'aligns', 'calculation', 'offerings', 'plan', 'breakdown', 'acceptance', 'miss', 'avoid', 'fit', 'contribution', 'factor', 'register', 'reconcile', 'maximum', 'split', 'enter', 'guarantee', 'commitments', 'decisions', 'clear', 'intake', 'warnings', 'approach', 'similar', 'responsibilities', 'necessary', 'articles', 'improved', 'combine', 'handling', 'need', 'formatting', 'publication', 'authoritative', 'scroll', 'freeze', 'input', 'performed', 'recovered', 'sequences', 'recorded', 'extend', 'main', 'affect', 'behave', 'copy', 'answer', 'variants', 'points', 'navigating', 'point', 'corrected', 'accesses', 'stages', 'obligations', 'progressed', 'qualified', 'precedence', 'deal', 'documented', 'fees', 'wide', 'submission', 'broken', 'managed', 'procedures', 'affecting', 'cultural', 'problem', 'linked', 'grouped', 'outstanding', 'prefer', 'correct', 'specialized', 'stalled', 'halted', 'link', 'occur', 'program', 'basis', 'higher', 'reserved', 'origin', 'stops', 'requires', 'registration', 'meet', 'structured', 'blocking', 'premium', 'forecasting', 'regulators', 'revisions', 'senior', 'activation', 'transmit', 'unresolved', 'giving', 'origins', 'contact', 'attach', 'get', 'identical', 'delayed', 'fail', 'apply', 'initiate', 'behavior', 'base', 'losing', 'holidays', 'including', 'authority', 'expected', 'exchanges', 'disposal', 'devices', 'consumption', 'use', 'different', 'flow', 'materials', 'official', 'trend', 'indicators', 'produced', 'unfinished', 'implemented', 'nearest', 'sponsored', 'stocking', 'meets', 'average', 'violations', 'logic', 'views', 'personal', 'allowed', 'discuss', 'shipping', 'exercise', 'charge', 'classify', 'quotas', 'corruption', 'decision', 'resolved', 'critical', 'fingerprints', 'answered', 'place', 'sign', 'important', 'markets', 'bundling', 'time', 'according', 'boost', 'grows', 'granted', 'informed', 'rated', 'move', 'ships', 'guidelines', 'moderation', 'blocks', 'issues', 'unlock', 'goes', 'transparent', 'spelling', 'containing', 'persists', 'organized', 'copies', 'streaming', 'partnerships', 'pricing', 'used', 'recommendations', 'remains', 'prepare', 'determined', 'labeling', 'contacts', 'reprint', 'questions', 'collect', 'rounding', 'interruption', 'selling', 'usage', 'distributions', 'anticipate', 'frequent', 'mistakes', 'suggestions', 'abandoned', 'discontinued', 'settled', 'redeem', 'b', 'communicate', 'earned', 'action', 'stopped', 'formatted', 'coordinated', 'cycles', 'competition', 'mind', 'redeeming', 'standing', 'experiences', 'lasts', 'strong', 'strengths', 'validity', 'transform', 'filing', 'separate', 'frequency', 'visualized', 'failures', 'launched', 'times', 'titles', 'desired', 'correlation', 'arranged', 'retrieval', 'friend', 'protocol', 'unique', 'specific', 'opinions', 'associated', 'busy', 'several', 'approvals', 'additions', 'solutions', 'privilege', 'tailor', 'structures', 'simple', 'push', 'resetting', 'returned', 'addressed', 'landing', 'differences', 'chats', 'bundled', 'last', 'retention', 'stolen', 'resets', 'delivered', 'explaining', 'operates', 'submissions', 'abuse', 'recovery', 'identities', 'charged', 'opened', 'friends', 'color', 'sale', 'errors', 'dimensions', 'warning', 'executive', 'scan', 'synchronized', 'integrated', 'express', 'waiting', 'cancelled', 'stay', 'followers', 'supports', 'easy', 'terms', 'offered', 'satisfied', 'enforced', 'local', 'performing', 'accessible', 'journey', 'referral', 'complex', 'reporting', 'sizes', 'good', 'reserve', 'monthly', 'disputes', 'statements', 'avoided', 'market', 'guidance', 'release', 'retrieve', 'flexible', 'approaching', 'measures', 'controls', 'segment', 'larger', 'third', 'right', 'reflect', 'legitimate', 'prepared', 'adoption', 'advanced', 'runs', 'dismissed', 'provide', 'appear', 'newest', 'perception', 'constraints', 'include', 'greater', 'destined', 'strength', 'backlog', 'preferred', 'welcome', 'abandonment', 'settle', 'corrupted', 'visibility', 'attacks', 'money', 'zoom', 'promote', 'captures', 'accept', 'consolidated', 'common', 'accounting', 'making', 'movements', 'preserve', 'models', 'emergency', 'restricted', 'balances', 'breaches', 'aligned', 'converted', 'operations', 'leaving', 'hours', 'conflicting', 'offsets', 'asked', 'links', 'internal', 'agree', 'identity', 'includes', 'developed', 'paths', 'vary', 'dispute', 'proceed', 'declarations', 'commissions', 'indicate', 'format', 'disputed', 'minimum', 'double', 'forms', 'directed', 'filings', 'operating', 'transparency', 'ordering', 'instructions', 'maintains', 'qualify', 'speed', 'start', 'aging', 'appearing', 'rotate', 'surprises', 'ownership', 'complaint', 'referring', 'consistent', 'incorrect', 'suits', 'resolves', 'joined', 'moderated', 'define', 'known', 'interruptions', 'determine', 'effect', 'exploration', 'altered', 'least', 'weight', 'error', 'standardized', 'find', 'communications', 'expand', 'choose', 'loyalty', 'blocked', 'findings', 'profit', 'movement', 'exchange', 'specifications', 'sets', 'presentations', 'issued', 'stage', 'backlogs', 'respond', 'understands', 'listed', 'packaging', 'performs', 'credits', 'shipped', 'fails', 'insights', 'mandatory', 'conversions', 'expired', 'close', 'books', 'run', 'inherit', 'begins', 'localized', 'lock', 'related', 'threats', 'end', 'touch', 'keys', 'benefit', 'exclusions', 'viewed', 'retrieved', 'assignment', 'pass', 'vote', 'highest', 'progress', 'expiring', 'margins', 'perform', 'central', 'keep', 'slow', 'entries', 'steps', 'tiers', 'assessment', 'approval', 'issue', 'recover', 'justified', 'reflects', 'gift', 'confirmation', 'maintenance', 'understood', 'connections', 'exact', 'synchronization', 'rights', 'messaging', 'long', 'defaults', 'overall', 'finance', 'stacking', 'accepted', 'appears', 'explanations', 'localize', 'coordinate', 'packed', 'explored', 'stays', 'individual', 'misleading', 'rates', 'target', 'cost', 'registrations', 'read', 'upheld', 'matched', 'responsible', 'attempted', 'reduce', 'empty', 'expect', 'discard', 'success', 'invited', 'emerging', 'delays', 'gave', 'minor', 'changed', 'treatment', 'capacity', 'maintain', 'notice', 'help', 'declared', 'modifying', 'missing', 'responding', 'inquiry', 'reply', 'posting', 'valuable', 'root', 'secure', 'reward', 'replies', 'damage', 'tolerate', 'streams', 'call', 'redemption', 'originating', 'typical', 'full', 'followed', 'authorities', 'next', 'manages', 'respected', 'changing', 'allowing', 'job', 'increases', 'leaves', 'complicated', 'packing', 'branding', 'drop', 'approximate', 'hide', 'duty', 'activated', 'pause', 'problems', 'buying', 'marketing', 'placed', 'act', 'boosts', 'occurs', 'inspected', 'renewal', 'limits', 'feels', 'costs', 'correlations', 'failure', 'real', 'planned', 'estimates', 'actions', 'brute', 'modified', 'unusual', 'appeared', 'name', 'exemption', 'paying', 'declined', 'actual', 'resolve', 'fake', 'remaining', 'zone', 'programs', 'human', 'exercised', 'correlate', 'optimize', 'post', 'staging', 'qualifying', 'bound', 'exclusive', 'cases', 'maturity', 'deletion', 'dynamic', 'encouraged', 'refined', 'planning', 'text', 'level', 'influence', 'reorder', 'running', 'considered', 'engine', 'space', 'zones', 'institutions', 'route', 'commission', 'combining', 'assessments', 'early', 'volume', 'ordered', 'editorial', 'translate', 'deducted', 'overrides', 'placing', 'drops', 'tests', 'transient', 'reservations', 'destination', 'purpose', 'occurring', 'handled', 'investigating', 'flash', 'limitations', 'synchronize', 'launches', 'change', 'abnormal', 'case', 'risk', 'print', 'set', 'readers', 'revoke', 'bought', 'periods', 'fresh', 'logging', 'knows', 'originate', 'handed', 'original', 'daily', 'connected', 'combined', 'made', 'pay', 'follows', 'withdrawal', 'guide', 'finished', 'routing', 'qualifies', 'cover', 'signed', 'sensitive', 'uses', 'assured', 'write', 'reaches', 'conflict', 'singular', 'past', 'associate', 'optimized', 'disrupt', 'embedded', 'clean', 'invite', 'tier', 'fulfills', 'captured', 'driven', 'matches', 'capture', 'connects', 'observed', 'force', 'encounter', 'matters', 'override', 'transported', 'documentation', 'persist', 'replaced', 'suspend', 'mark', 'social', 'take', 'business', 'excluded', 'schemes', 'registers', 'competitive', 'charts', 'communicated', 'notes', 'arrival', 'segments', 'completes', 'length', 'redeemed', 'minimized', 'reason', 'cheaper', 'conducted', 'recurring', 'promoted', 'fast', 'experience', 'variations', 'measure', 'targets', 'drive', 'consider', 'declaration', 'subscribed', 'inactivity', 'mismatched', 'loss', 'upgrades', 'recommendation', 'manual', 'preserved', 'immediate', 'enjoy', 'consume', 'deductions', 'capability', 'visualize', 'expanded', 'replay', 'stronger', 'wait', 'seamless', 'effective', 'calculations', 'stories', 'happened', 'anomalies', 'fall', 'tries', 'installments', 'valued', 'remember', 'block', 'commerce', 'missed', 'positive', 'lineage', 'voice', 'view', 'site', 'checks', 'characteristics', 'convert', 'overload', 'expansion', 'extra', 'specify', 'condition', 'intelligence', 'growth', 'broaden', 'leadership', 'scope', 'delivering', 'lose', 'cross', 'deviations', 'share', 'audiences', 'learn', 'closest', 'functional', 'issuing', 'expiration', 'savings', 'becomes', 'trails', 'closure', 'loyal', 'barriers', 'suppression', 'propagate', 'progresses', 'adjustments', 'attention', 'shared', 'regarding', 'engagement', 'delay', 'moved', 'vacation', 'friction', 'forget', 'examined', 'restrict', 'interpret', 'tracing', 'conventions', 'traffic', 'deals', 'secured', 'want', 'using', 'broadcast', 'lower', 'partial', 'explain', 'outgoing', 'collection', 'community', 'confirming', 'instant', 'screen', 'regular', 'prohibited', 'award', 'appropriate', 'distribute', 'require', 'requiring', 'easier', 'better', 'organize', 'understand', 'large', 'applied', 'leave', 'certifications', 'spending', 'routed', 'rewards', 'starts', 'quick', 'device', 'implement', 'major', 'serious', 'negative', 'safeguards', 'guest', 'aggregated', 'entire', 'improvements', 'complete', 'reconciled', 'connect', 'design', 'side', 'infinite', 'adjusted', 'contain', 'subscribe', 'bar', 'audience', 'scaling', 'obtain', 'depth', 'solve', 'attack', 'standards', 'highlight', 'short', 'grouping', 'behaviors', 'modification', 'finishes', 'authorizations', 'best', 'control', 'try', 'transfer', 'evidence', 'external', 'transfers', 'sells', 'contributions', 'inform', 'needs', 'jobs', 'navigate', 'editing', 'supply', 'detail', 'attempts', 'stand', 'behaves', 'applying', 'manage', 'risks', 'refine', 'withdraw', 'severity', 'stability', 'lost', 'registering', 'provides', 'begin', 'tasks', 'handle', 'rate', 'cash', 'go', 'suggested', 'complaints', 'make', 'dispatched', 'visits', 'question', 'cycle', 'replacement', 'repeat', 'navigation', 'book', 'correction', 'reliable', 'authorized', 'repeated', 'demonstrated', 'disconnect', 'attract', 'comparison', 'suggest', 'attached', 'agreements', 'increase', 'assist', 'recognize', 'corresponds', 'plans', 'compromised', 'switching', 'chain', 'analysis', 'established', 'referrals', 'needed', 'gaps', 'placement', 'affiliate', 'acceptable', 'letter', 'resistant', 'terminate', 'limited', 'presentation', 'withdrawals', 'returning', 'churn', 'damaged', 'misused', 'retain', 'counting', 'controlled', 'network', 'activate', 'balance', 'arrange', 'smooth', 'required', 'scale', 'preview', 'future', 'know', 'personalized', 'answers', 'become', 'labeled', 'throttling', 'changes', 'trust', 'formats', 'sold', 'calls', 'transit', 'hour', 'posted', 'acknowledgment', 'shopping', 'self', 'causes', 'tailored', 'size', 'floors', 'list', 'confirmations', 'decrease', 'broader', 'notices', 'contents', 'forward', 'holiday', 'describing', 'reach', 'transformations', 'canceled', 'invalid', 'included', 'investments', 'rest', 'protocols', 'low', 'simulate', 'networks', 'stable', 'badges', 'based', 'quicker', 'select', 'incompatible', 'reminder', 'bounce', 'single', 'guides', 'ends', 'follow', 'creation', 'speeds', 'performance', 'edit', 'involving', 'handles', 'names', 'cancel', 'privileged', 'detection', 'small', 'seasons', 'defective', 'unsafe', 'interest', 'readiness', 'abandon', 'installment', 'look', 'fair', 'unused', 'friendly', 'complementary', 'republishing', 'remove', 'way', 'assess', 'locked', 'reset', 'incorporated', 'removed', 'limit', 'defined', 'cleared', 'decline', 'default', 'recent', 'mitigated', 'collections', 'safety', 'credit', 'poor', 'journeys', 'advantage', 'old', 'amended', 'ready', 'consistency', 'visit', 'compatible', 'distribution', 'designs', 'sample', 'attempt', 'special', 'met', 'budget', 'forgotten', 'historical', 'describe', 'writing', 'adjust', 'viewing', 'acquisition', 'balanced', 'supported', 'faster', 'progression', 'accompany', 'discover', 'histories', 'alternative', 'interests', 'drives', 'collected', 'turnover', 'weaknesses', 'maintained', 'indicated', 'locate', 'moderate', 'chat', 'overwhelm', 'respect', 'lists', 'browsing', 'bottlenecks', 'transmitted', 'explore', 'stop', 'chosen', 'makes', 'portal', 'assignments', 'legal', 'signals', 'popular', 'exclude', 'weekly', 'progressing', 'assessed', 'impact', 'initiating', 'judge', 'later', 'found', 'picking', 'sell', 'focused', 'grant', 'align', 'compensation', 'ranges', 'automatic', 'conversion', 'decide', 'recommend', 'lag', 'material', 'expands', 'step', 'continue', 'traced', 'enterprise', 'suspension', 'occurred', 'agreement', 'currencies', 'association', 'supporting', 'starting', 'inspect', 'sequence', 'international', 'bypass', 'resolution', 'conditions', 'breakdowns', 'purposes', 'introductory', 'dominate', 'matching', 'intervals', 'opinion', 'customs', 'incoming', 'reduced', 'flagged', 'narrow', 'closing', 'quarantine', 'operational', 'lawful', 'violation', 'gain', 'ship', 'taken', 'clearance', 'plural', 'released', 'words', 'sales', 'duties', 'levels', 'timers', 'funnels', 'replace', 'confidence', 'protections', 'charges', 'rich', 'click', 'check', 'concerns', 'intended', 'key', 'tied', 'votes', 'asking', 'fulfilled', 'offenses', 'benefits', 'digital', 'recording', 'written', 'requirements', 'presence', 'retained', 'picked', 'doubts', 'laws', 'warns', 'period', 'detailed', 'happen', 'lowest', 'confirm', 'reasons', 'featured', 'engines', 'dependent', 'obligation', 'expectations', 'conflicts', 'confirmed', 'bulk', 'added', 'spikes', 'allows', 'possible', 'correcting', 'reminders', 'browse', 'checked', 'expert', 'volumes', 'propagated', 'provided', 'corrective', 'mode', 'high', 'edits', 'combination', 'intervention', 'rapid'}
NON_VAGUE_WORDS = {
'exchanged','trusted','initiated','previews','remain','resume','pickups','sharing',
'suspended','trends','edited','placements','selection','reflected','adding',
'acknowledge','misuse','spam','coordination','execution','log','arrivals',
'translated','alignment','timing','structure','irregularities','deliver',
'recommended','fee','live','integrate','acknowledgments','transitions',
'started','correspondence','acknowledged','protection','requested','standard',
'launch','registered','accessories','persistent','render','capabilities',
'oversight','responsibility','continues','coverage','screens','transferred',
'revised','expense','funds','peak','selections','operate','reported',
'training','measured','marked','persistence','corrections','fulfill','match',
'connection','indexing','testing','taxonomy','replacements','storage','parallel',
'tools','protected','requesting','destinations','focus','patterns','scoring',
'ranking','budgets','posture','modifications','typing','quality','timely',
'exposure','verify','contains','modify','merge','satisfaction','denied',
'duplicate','resolutions','automation','preparation','distributed','units',
'explanation','stream','communication','demand','task','normalize','inquiries',
'violate','pays','aligns','calculation','offerings','plan','breakdown',
'acceptance','avoid','contribution','register','reconcile','split','enter',
'commitments','decisions','clear','intake','warnings','approach',
'responsibilities','articles','improved','combine','handling','formatting',
'publication','scroll','freeze','input','performed','recovered','sequences',
'recorded','extend','affect','copy','answer','variants','points','point',
'corrected','accesses','stages','obligations','qualified','documented','fees',
'submission','managed','procedures','linked','grouped','specialized','link',
'program','basis','reserved','origin','stops','requires','registration',
'structured','blocking','premium','forecasting','revisions','activation',
'transmit','unresolved','contact','attach','identical','delayed','fail',
'apply','initiate','behavior','base','including','authority','expected',
'exchanges','disposal','devices','consumption','materials','official','trend',
'indicators','produced','implemented','sponsored','stocking','average',
'violations','logic','views','allowed','shipping','charge','classify',
'decision','resolved','critical','answered','place','markets','bundling',
'time','boost','granted','informed','rated','move','ships','guidelines',
'moderation','blocks','issues','unlock','transparent','spelling','containing',
'persists','organized','copies','streaming','partnerships','pricing','used',
'recommendations','prepare','determined','labeling','contacts','questions',
'collect','rounding','selling','usage','distributions','frequent','mistakes',
'suggestions','abandoned','discontinued','settled','redeem','communicate',
'earned','action','stopped','formatted','coordinated','cycles','competition',
'experiences','strengths','validity','transform','filing','separate',
'frequency','visualized','failures','launched','times','titles','correlation',
'arranged','retrieval','protocol','unique','specific','associated','approvals',
'additions','solutions','privilege','structures','push','resetting','returned',
'addressed','landing','differences','chats','bundled','retention','resets',
'delivered','explaining','operates','submissions','abuse','recovery',
'identities','charged','opened','color','sale','errors','dimensions','warning',
'scan','synchronized','integrated','waiting','cancelled','followers',
'supports','terms','offered','enforced','local','performing','accessible',
'journey','referral','reporting','sizes','reserve','monthly','disputes',
'statements','market','guidance','release','retrieve','measures','controls',
'segment','right','reflect','prepared','adoption','advanced','runs',
'provide','appear','constraints','include','backlog','preferred','visibility',
'attacks','money','promote','captures','consolidated','common','accounting',
'making','movements','preserve','models','restricted','balances','breaches',
'aligned','converted','operations','hours','conflicting','offsets','links',
'internal','identity','includes','developed','paths','vary','dispute',
'proceed','declarations','commissions','indicate','format','disputed',
'forms','directed','filings','operating','transparency','ordering',
'instructions','maintains','qualify','speed','start','rotate','ownership',
'complaint','consistent','incorrect','resolves','joined','moderated','define',
'known','determine','effect','altered','weight','error','standardized','find',
'communications','expand','choose','loyalty','blocked','findings','profit',
'movement','exchange','specifications','sets','issued','stage','respond',
'listed','packaging','performs','credits','shipped','fails','insights',
'mandatory','conversions','expired','close','run','begins','localized','lock',
'related','threats','end','keys','benefit','viewed','retrieved','assignment',
'pass','progress','expiring','perform','keep','entries','steps','tiers',
'assessment','approval','issue','recover','reflects','gift','confirmation',
'maintenance','connections','synchronization','rights','messaging','defaults',
'overall','finance','accepted','appears','localize','coordinate','packed',
'stays','rates','target','cost','registrations','read','matched',
'responsible','attempted','reduce','empty','expect','discard','success',
'delays','capacity','maintain','notice','help','declared','missing',
'responding','inquiry','reply','posting','secure','reward','replies','damage',
'streams','call','redemption','followed','authorities','manages','respected',
'job','increases','packing','branding','drop','duty','activated','pause',
'buying','marketing','placed','boosts','occurs','inspected','renewal','limits',
'costs','failure','planned','estimates','actions','modified','unusual','name',
'exemption','declined','actual','resolve','remaining','zone','programs',
'deletion','dynamic','encouraged','refined','planning','text','level',
'reorder','running','engine','route','commission','assessments','volume',
'ordered','editorial','translate','deducted','overrides','placing','drops',
'tests','reservations','destination','handled','investigating','flash',
'limitations','synchronize','launches','change','abnormal','case','risk',
'print','set','revoke','periods','logging','original','daily','connected',
'combined','pay','follows','withdrawal','guide','finished','routing',
'qualifies','signed','sensitive','uses','write','reaches','conflict',
'associate','embedded','clean','tier','captured','matches','capture',
'connects','observed','documentation','persist','replaced','suspend','mark',
'social','business','excluded','schemes','registers','competitive','charts',
'communicated','notes','arrival','segments','completes','length','redeemed',
'conducted','recurring','promoted','experience','variations','measure',
'targets','consider','declaration','subscribed','inactivity','mismatched',
'loss','upgrades','recommendation','manual','preserved','immediate','consume',
'deductions','visualize','expanded','replay','effective','calculations',
'anomalies','installments','block','commerce','lineage','voice','view','site',
'checks','convert','overload','expansion','intelligence','growth','scope',
'delivering','share','audiences','learn','issuing','expiration','savings',
'becomes','trails','closure','suppression','progresses','adjustments',
'attention','shared','engagement','delay','moved','friction','restrict',
'interpret','tracing','traffic','deals','using','broadcast','partial',
'explain','collection','community','confirming','screen','regular',
'prohibited','appropriate','distribute','require','easier','organize',
'understand','applied','certifications','spending','routed','rewards',
'starts','device','implement','aggregated','improvements','complete',
'reconciled','connect','design','adjusted','contain','subscribe','obtain',
'depth','solve','standards','highlight','grouping','behaviors','modification',
'finishes','control','transfer','evidence','external','transfers','inform',
'jobs','navigate','editing','supply','detail','attempts','applying','manage',
'risks','refine','severity','stability','registering','provides','begin',
'tasks','handle','rate','cash','suggested','complaints','dispatched','visits',
'question','cycle','replacement','repeat','navigation','correction',
'reliable','authorized','repeated','demonstrated','comparison','suggest',
'attached','agreements','increase','assist','recognize','plans','analysis',
'established','referrals','needed','placement','affiliate','acceptable',
'limited','withdrawals','returning','churn','damaged','retain','controlled',
'network','activate','balance','required','scale','preview','future','know',
'personalized','answers','changes','trust','formats','sold','calls','transit',
'posted','shopping','tailored','size','list','confirmations','decrease',
'notices','contents','forward','reach','canceled','included','protocols',
'stable','badges','based','select','reminder','single','guides','ends',
'follow','creation','performance','edit','involving','handles','names',
'cancel','detection','seasons','defective','interest','readiness','installment',
'remove','reset','removed','limit','defined','cleared','decline','default',
'collections','safety','credit','ready','consistency','visit','compatible',
'distribution','attempt','historical','adjust','viewing','acquisition',
'balanced','supported','faster','progression','discover','histories',
'alternative','interests','collected','maintained','indicated','locate',
'moderate','chat','respect','lists','browsing','transmitted','explore','stop',
'chosen','portal','assignments','legal','signals','popular','weekly',
'progressing','assessed','impact','initiating','found','picking','sell',
'focused','grant','align','automatic','conversion','decide','recommend',
'continue','traced','suspension','occurred','agreement','currencies',
'association','supporting','starting','inspect','sequence','international',
'bypass','resolution','conditions','breakdowns','matching','intervals',
'customs','incoming','reduced','flagged','operational','lawful','violation',
'gain','ship','taken','clearance','released','sales','duties','levels',
'timers','replace','confidence','charges','click','check','concerns','key',
'votes','fulfilled','benefits','digital','recording','written','requirements',
'presence','retained','picked','laws','period','detailed','happen','confirm',
'reasons','featured','dependent','confirmed','bulk','added','spikes','allows',
'possible','reminders','browse','checked','volumes','provided','mode','high',
'edits','combination','rapid'
}

print(len(listx))
print(len(NON_VAGUE_WORDS))
print(len(intersection(listx, NON_VAGUE_WORDS)))
print(len(difference(listx, NON_VAGUE_WORDS)))
print(difference(listx, NON_VAGUE_WORDS))